# Generated by Django 4.0.7 on 2022-09-23 01:40

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCI_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', fernet_fields.fields.EncryptedCharField(max_length=100)),
            ],
        ),
    ]
